feat: provide basic feature
webp-sh/halo-plugin-webp-cloud pull request #1
Opened 2023-06-28 02:36 UTC by ruibaby

This PR initializes the basic information of the plugin and provides image path replacement in the post.

2023-06-28 02:42 UTC, JohnNiang requested changes

2023-06-28 02:42 UTC, JohnNiang commented on lib/api-2.7.0-SNAPSHOT.jar
建议移除无用的文件。

2023-06-29 04:13 UTC, JohnNiang commented on src/main/java/se/webp/plugin/WebpCloudPostContentHandler.java
> +        String api_key;
建议将 api_key 保存到 Secret 中，而不是 Setting 中。

2023-06-29 04:40 UTC, ruibaby commented on src/main/java/se/webp/plugin/WebpCloudPostContentHandler.java
> +        String api_key;
但现在不支持 Secret 管理。这个 api_key 暂时没用到，可以先去掉。

2023-06-29 07:04 UTC, JohnNiang approved these changes
LGTM

Hi @n0vad3v , please take a moment to have a look.

2023-06-29 09:42 UTC, merged